folderDatasource:
  object: FolderDatasource
  path: testdata

  sampleCircles:
    object: Sample
    circles: 
      object: Circle
      x: 0
      y: 0

server:
  object: Server
  port: 8089
  datasource: "@/folderDatasource"
  schema:
    object: Schema

    "GET|WatchCircles/:watcherId":
      object: ActionWatch
      websocket: true
      query:
        circles: null

    "GET|MoveCircles":
      object: ActionSet
      mergeInput: false
      query:
        circles: 
          x: :random({number:1,500})
          y: :random({number:1,500})

    "GET|res/:filename":
      object: ActionResourceGet
      directory: ""

    "GET|index.html":
      object: Page
      html: |
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Forjitree JS</title>
          <script src="/res/forjitree.js"></script>
        </head>
        <body>
        <script>
          class Circle {
            constructor(node) {
              this.node = node
              console.log('Circle created')
            }

            Updated(key, value) {
              console.log('Circle updated')
            }
          }

          let Config = new DatasourceClient(null)
          Config.Tree.AddType(Circle, 'Circle')
          Config.websocket = true
          Config.url = "wss://training.place/WatchCircles"
          Config.Created()
        </script>
        </body>
        </html>
