folderDatasource:
  object: FolderDatasource
  path: testdata

  sampleStarship:
    object: Sample
    starship: 
      object: Starship
      x: 0
      y: 0
      z: 0

server:
  object: Server
  port: 8089
  datasource: "@/folderDatasource"
  schema:
    object: Schema

    "GET|WatchStarship/:watcherId":
      object: ActionWatch
      websocket: true
      query:
        starship: null

    "GET|MoveStarship/:watcherId":
      object: ActionSet
      mergeInput: false
      query:
        starship: 
          x: :random({number:1,100})
          y: :random({number:1,100})
          z: :random({number:1,100})

    "GET|res/:filename":
      object: ActionResourceGet
      directory: ""

    "GET|index.html":
      object: Page
      html: |
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Forjitree JS</title>
          <script src="/res/forjitree.js"></script>
        </head>
        <body>
        <script>
          let Config = new DatasourceClient(null)
          Config.websocket = true
          Config.url = "wss://training.place/WatchStarship"
          Config.Created()
        </script>
        </body>
        </html>
